[[constraint]]
  name = "github.com/bwmarrin/discordgo"
  version = "0.19.0"

[[constraint]]
  name = "github.com/hakasec/jmdict-go"
  version = "0.1.0"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.9.0"

[prune]
  go-tests = true
  unused-packages = true
